---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmchartconfig.yaml
  - certificate.yaml
  - middleware-oauth2-proxy.yaml
  - middleware-rate-limit.yaml
  - pod-monitor.yaml
