---
# Argo CD's certificate for Traefik, issued separately rather than through Ingress annotations
# (as for Zitadel's auth-tls).
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.d3strukt0r.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
